---
# tasks file for nginx
 - name: Install epel-release if needed packages 
   yum:
     name: 
      - "epel-release"
     state: latest
   when: 
      - ansible_os_family == "RedHat"
      - ansible_distribution_major_version == "7"

 - name: Install nginx packages 
   yum:
     name: 
      - "nginx"
     state: latest

 ### PHP only valid for molecule nginx config testing
 - name: Install test php-fpm packages 
   yum:
     name: 
      - "php-fpm"
     state: latest
   when: molecule_yml is  defined
  
 - name: Nginx root additional dir create
   file:
    path: "{{ webroot }}"
    state: directory
    mode: '0755'


 - name: PHP fpm runtime www.sock dir
   file:
    path: /run/php-fpm/
    state: directory
    mode: '0755'
   notify:  restart_php
   when: molecule_yml is  defined  

 - name: Configure index.php main page template
   template:
      src: index.php.j2
      dest: "{{ webroot }}/index.php"
      backup: yes
      mode: '0755'
   

 - name: Nginx additional config dir exist     
   stat:
      path: /etc/nginx/http.d
   register: stat_root_result    
     
 - name: Nginx additional dir create
   file:
    path: /etc/nginx/http.d
    state: directory
    mode: '0600'   
   when: not stat_root_result.stat.exists

 - name: Configure nginx main conf from template
   template:
      src: nginx.j2
      dest: /etc/nginx/nginx.conf
      backup: yes
      mode: '0600'


 - name: Configure nginx http conf from template
   template:
      src: nginx_http.j2
      dest: /etc/nginx/http.d/nginx.conf
      backup: yes
      mode: '0755'
   notify: restart_nginx




   


