---
# tasks file for php
- name: Install php-fpm packages 
  yum:
     name: 
      - "php-fpm"
     state: latest
  
- name: PHP-FPM document root additional dir create
  file:
    path: "{{ webroot }}"
    state: directory
    mode: '0755'
  notify: restart_php 

- name: Configure index.php main page template
  template:
    src: index.php.j2
    dest: "{{ webroot }}/index.php"
    backup: yes
    mode: '0755'
  notify: restart_php  

- name: Configure php-fpm.www.conf template
  template:
    src: php.www.conf.j2
    dest: /etc/php-fpm.d/www.conf
    backup: yes
    mode: '0600'
  notify: restart_php


 