---
# tasks file for php
- name: Install test php-fpm packages 
  yum:
     name: 
      - "php-fpm"
     state: latest
  

- name: Configure php-fpm.www.conf template
  template:
    src: php.www.conf.j2
    dest: /etc/php-fpm.d/www.conf
    backup: yes
    mode: '0600'
  notify: restart_php


 